kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: ptarmiganlabs/butler-sos
    dockerfile: Dockerfile
    context: 
    # auto_tag: true
    tags:
    - latest
    - '5.2.0'
    - '5.2'
    - '5'
  when:
    event:
    - tag
