Butler-SOS:
  # Logging configuration
  logLevel: debug          # Log level. Possible log levels are silly, debug, verbose, info, warn, error
  fileLogging: true       # true/false to enable/disable logging to disk file
  logDirectory: logs      # Subdirectory where log files are stored
  
  # Qlik Sense logging db config parameters
  logdb:
    enableLogDb: true
    influxDbRetentionPolicy: DEFAULT
    pollingInterval: 15000    # How often (milliseconds) should Postgres log db be queried for warnings and errors?
    queryPeriod: 3 minutes    # How far back should Butler SOS query for log entries? Default is 5 min
    host: pro2-win1.ptarmiganlabs.net
    port: 4432
    qlogsReaderUser: qlogs_reader
    qlogsReaderPwd: aTEM7TcwagA
    extractErrors: true       # Should error level entries be extracted from log db into Influxdb?
    extractWarnings: true     # Should warn level entries be extracted from log db into Influxdb?
    extractInfo: true         # Should info level entries be extracted from log db into Influxdb?

  # Certificates to use when querying Sense for healthcheck data. Get these from the Certificate Export in QMC.
  cert:
    # clientCert: /nodeapp/config/certificate/client.pem
    # clientCertKey: /nodeapp/config/certificate/client_key.pem
    # clientCertCA: /nodeapp/config/certificate/root.pem
    clientCert: /Users/goran/code/secret/pro2-win1/pro2-win1/client.pem
    clientCertKey: /Users/goran/code/secret/pro2-win1/pro2-win1/client_key.pem
    clientCertCA: /Users/goran/code/secret/pro2-win1/pro2-win1/root.pem

  # MQTT config parameters
  mqttConfig:
    enableMQTT: true
    brokerHost: 192.168.100.20
    brokerPort: 1883
    baseTopic: butler-sos/          # Topic should end with /

  # Influx db config parameters
  influxdbConfig:
    enableInfluxdb: true
    hostIP: 192.168.1.51
    dbName: SenseOps
    # Control whether certain fields are stored in InfluxDB or not
    # Use with caution! Enabling activeDocs, loadedDocs or inMemoryDocs may result in lots of data sent to InfluxDB.
    includeFields:
      activeDocs: true              # Should data on what docs are active be stored in Influxdb?
      loadedDocs: true              # Should data on what docs are loaded be stored in Influxdb?
      inMemoryDocs: true            # Should data on what docs are in memory be stored in Influxdb?

  # Sessions per virtual proxy
  userSessions:
    enableSessionExtract: true                      # Query  unique user IDs of what users have sessions open (true/false)?
    pollingInterval: 10000                          # How often (milliseconds) should session data be polled?
    influxDbRetentionPolicy: 7days
    servers:                                        # What hosts and including virtual proxies, should we get sessions for?
      - host: pro2-win1.ptarmiganlabs.net:4243      
        virtualProxy:                               # Default virtual proxy
      - host: pro2-win1.ptarmiganlabs.net:4243
        virtualProxy: /hdr

  serversToMonitor:
    pollingInterval: 15000           # How often (milliseconds) should the healthcheck API be polled?
    influxDbRetentionPolicy: 14days

    # List of extra tags for each server. Useful for creating more advanced Grafana dashboards.
    # Each server below MUST include these tags in its serverTags property.
    # The tags below are just examples - define your own as needed
    serverTagsDefinition: 
      - server_group
      - serverLocation
      - server-type
      - serverBrand

    # Sense Servers that should be queried for healthcheck data 
    servers:
      - host: pro2-win1.ptarmiganlabs.net:4747
        serverName: sense1
        serverDescription: Central
        logDbHost: pro2-win1
        serverTags:
          server_group: CENTRAL
          serverLocation: Europe
          server-type: virtual
          serverBrand: HP
    # - host: pro1-win2.ptarmiganlabs.net:4747
    #   serverName: sense2
    #   serverDescription: Dev server 1
    #   logDbHost: win2
    #   serverTags:
    #     server_group: DEV
    #     serverLocation: Europe
    #     server-type: virtual
    #     serverBrand: HP
    # - host: pro1-win3.ptarmiganlabs.net:4747
    #   serverName: sense3
    #   serverDescription: Dev server 2
    #   logDbHost: win3
    #   serverTags:
    #     server_group: DEV
    #     serverLocation: US
    #     server-type: physical
    #     serverBrand: Dell
    # - host: pro1-win4.ptarmiganlabs.net:4747
    #   serverName: sense4
    #   serverDescription: QA server 1
    #   logDbHost: win4
    #   serverTags:
    #     server_group: QA
    #     serverLocation: Sweden
    #     server-type: physical
    #     serverBrand: HP

    # - host: sense1.int.ptarmiganlabs.net:4747
    #   serverName: sense2
    #   serverDescription: Central2 
    #   logDbHost: sense2
    #   influxTags:
    #     serverGroup: DEV2
    # - host: sensedev.int.ptarmiganlabs.net:4747
    #   serverName: sensedev
    #   serverDescription: Dev node
    #   logDbHost: sensedev
    #   influxTags:
    #     serverGroup: DEV
