Butler-SOS:
  # Possible log levels are silly, debug, verbose, info, warn, error
  logLevel: verbose

  # Qlik Sense logging db config parameters
  logdb:
    enableLogDb: true
    # How often (milliseconds) should Postgres log db be queried for warnings and errors?
    pollingInterval: 60000
    # How far back should Butler SOS query for log entries? Default is 5 min
    queryPeriod: 5 minutes
    host: <IP or FQDN of Qlik Sense logging db>
    port: 4432
    qlogsReaderUser: qlogs_reader
    qlogsReaderPwd: <pwd>

  # Certificates to use when querying Sense for healthcheck data. Get these from the Certificate Export in QMC.
  cert:
    clientCert: <path/to/cert/client.pem>
    clientCertKey: <path/to/cert/client_key.pem>
    clientCertCA: <path/to/cert/root.pem>

  # MQTT config parameters
  mqttConfig:
    enableMQTT: true
    brokerHost: <IP of MQTT server>
    brokerPort: 1883
    # Topic should end with /
    baseTopic: butler-sos/

  # Influx db config parameters
  influxdbConfig:
    enableInfluxdb: true
    hostIP: <IP or FQDN of Influxdb server>
    dbName: SenseOps
    # Control whether certain fields are stored in InfluxDB or not
    # Use with caution! Enabling activeDocs, loadedDocs or inMemoryDocs may result in lots of data sent to InfluxDB.
    includeFields:
      activeDocs: false
      loadedDocs: false
      inMemoryDocs: false

  serversToMonitor:
    # How often (milliseconds) should the healthcheck API be polled? 
    pollingInterval: 30000

    # Sense Servers that should be queried for healthcheck data 
    servers:
    - host: <server1.my.domain>
      serverName: <server1>
      influxTags:
        serverGroup: DEV
    - host: <server2.my.domain>
      serverName: <server2>
      influxTags:
        serverGroup: PROD
