Butler-SOS:
  # Logging configuration
  logLevel: info          # Log level. Possible log levels are silly, debug, verbose, info, warn, error
  fileLogging: true       # true/false to enable/disable logging to disk file
  logDirectory: logs      # Subdirectory where log files are stored

  # Qlik Sense logging db config parameters
  logdb:
    enableLogDb: true
    pollingInterval: 60000    # How often (milliseconds) should Postgres log db be queried for warnings and errors?
    queryPeriod: 5 minutes    # How far back should Butler SOS query for log entries? Default is 5 min
    host: <IP or FQDN of Qlik Sense logging db>
    port: 4432
    qlogsReaderUser: qlogs_reader
    qlogsReaderPwd: <pwd>
    extractErrors: true       # Should error level entries be extracted from log db into Influxdb?
    extractWarnings: true     # Should warn level entries be extracted from log db into Influxdb?
    extractInfo: true         # Should info level entries be extracted from log db into Influxdb?

  # Certificates to use when querying Sense for healthcheck data. Get these from the Certificate Export in QMC.
  cert:
    clientCert: <path/to/cert/client.pem>
    clientCertKey: <path/to/cert/client_key.pem>
    clientCertCA: <path/to/cert/root.pem>
    # If running Butler in a Docker container, the cert paths MUST be the following
    # clientCert: /nodeapp/config/certificate/client.pem
    # clientCertKey: /nodeapp/config/certificate/client_key.pem
    # clientCertCA: /nodeapp/config/certificate/root.pem

  # MQTT config parameters
  mqttConfig:
    enableMQTT: false
    brokerHost: <IP of MQTT server>
    brokerPort: 1883
    baseTopic: butler-sos/          # Topic should end with /

  # Influx db config parameters
  influxdbConfig:
    enableInfluxdb: true
    hostIP: <IP or FQDN of Influxdb server>
    dbName: SenseOps
    # Control whether certain fields are stored in InfluxDB or not
    # Use with caution! Enabling activeDocs, loadedDocs or inMemoryDocs may result in lots of data sent to InfluxDB.
    includeFields:
      activeDocs: false              # Should data on what docs are active be stored in Influxdb (true/false)? 
      loadedDocs: false              # Should data on what docs are loaded be stored in Influxdb (true/false)?
      inMemoryDocs: false            # Should data on what docs are in memory be stored in Influxdb (true/false)?
      userIds: true                  # Extract and store in Influxdb unique user IDs of what users have sessions open (true/false)?

  serversToMonitor:
    pollingInterval: 30000      # How often (milliseconds) should the healthcheck API be polled?

    # List of extra tags for each server. Useful for creating more advanced Grafana dashboards.
    # Each server below MUST include these tags in its serverTags property.
    # The tags below are just examples - define your own as needed
    serverTagsDefinition: 
      - server_group
      - serverLocation
      - server-type
      - serverBrand

    # Sense Servers that should be queried for healthcheck data 
    servers:
    - host: <server1.my.domain>
      serverName: <server1>
      serverDescription: <description>
      logDbHost: <host name as used in QLogs db>
      serverTags:
        server_group: DEV
        serverLocation: Asia
        server-type: virtual
        serverBrand: Dell
    - host: <server2.my.domain>
      serverName: <server2>
      serverDescription: <description>
      logDbHost: <host name as used in QLogs db>
      serverTags:
        server_group: PROD
        serverLocation: Europe
        server-type: physical
        serverBrand: HP
 